default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/simple_loads.sqlite3

test:
  <<: *default
  database: db/simple_loads_test.sqlite3

production:
  <<: *default
  database: db/simple_loads.sqlite3
